import Header from "./Header";
import Footer from "./Footer";
import Home from "./Home";
import Baner from "./Baner";
import News from "./News";
import NewArival from "./NewArival";
import Cart from "./Cart";
import BestSeller from "./BestSeller";
import Login_Register from "./Login_Register";
import Giohang from "./Giohang";
export {Header,Footer,Home,Baner, News,NewArival,Cart,BestSeller ,Login_Register,Giohang}